"""Faithful finite-inventory GLFT benchmark.

This module implements the closed-form reduction in Guéant, Lehalle and
Fernandez-Tapia.  It is deliberately a *theoretical* benchmark: fills are
independent Poisson arrivals with intensity ``A * exp(-k * delta)``.  Queue
priority, latency, adverse selection and market-data replay belong in a
separate empirical execution model.

Units are consistent when time is expressed in one common unit and price in
one common currency unit: ``A`` is 1/time; ``k`` and ``gamma`` are 1/price;
``sigma`` is price/sqrt(time); and ``mu`` is price/time.  Consequently the
matrix below is 1/time, its exponential is dimensionless, and quote deltas
are prices.
"""

from __future__ import annotations

import math
from dataclasses import dataclass
from functools import lru_cache
from numbers import Integral

import numpy as np
from numpy.typing import NDArray
from scipy.linalg import expm

THEORETICAL_BENCHMARK_LABEL = "GLFT theoretical benchmark (independent Poisson fills)"


@dataclass(frozen=True, slots=True)
class GLFTParameters:
    """Parameters of the finite-inventory GLFT model."""

    A: float
    k: float
    gamma: float
    sigma: float
    max_inventory: int
    mu: float = 0.0

    def __post_init__(self) -> None:
        finite_values = (self.A, self.k, self.gamma, self.sigma, self.mu)
        if not all(math.isfinite(value) for value in finite_values):
            raise ValueError("GLFT parameters must be finite")
        if self.A <= 0.0:
            raise ValueError("A must be strictly positive")
        if self.k <= 0.0:
            raise ValueError("k must be strictly positive")
        if self.gamma <= 0.0:
            raise ValueError("gamma must be strictly positive")
        if self.sigma < 0.0:
            raise ValueError("sigma cannot be negative")
        if (
            isinstance(self.max_inventory, bool)
            or not isinstance(self.max_inventory, Integral)
            or self.max_inventory < 1
        ):
            raise ValueError("max_inventory must be a positive integer")


@dataclass(frozen=True, slots=True)
class GLFTConstants:
    """Constants appearing in the GLFT linear system."""

    c: float
    eta: float
    alpha: float
    beta: float


@dataclass(frozen=True, slots=True)
class QuoteDeltas:
    """Optimal distances from mid; ``None`` means inventory forbids the side."""

    bid_delta: float | None
    ask_delta: float | None


@dataclass(frozen=True, slots=True)
class TheoreticalPoissonSimulation:
    """Path generated by the explicitly simplified GLFT Poisson benchmark.

    State arrays have length ``len(time)``.  Quote and fill arrays describe
    each interval ``[time[i], time[i + 1])`` and therefore have length one
    less.  A missing quote at an inventory boundary is stored as ``nan``.
    """

    label: str
    seed: int
    time: NDArray[np.float64]
    step_duration: NDArray[np.float64]
    mid_price: NDArray[np.float64]
    inventory: NDArray[np.int64]
    cash: NDArray[np.float64]
    equity: NDArray[np.float64]
    bid_delta: NDArray[np.float64]
    ask_delta: NDArray[np.float64]
    bid_price: NDArray[np.float64]
    ask_price: NDArray[np.float64]
    bid_fills: NDArray[np.int64]
    ask_fills: NDArray[np.int64]


def glft_constants(parameters: GLFTParameters) -> GLFTConstants:
    """Return the exact constants used by the GLFT finite-horizon solution."""

    ratio_log = math.log1p(parameters.gamma / parameters.k)
    return GLFTConstants(
        c=ratio_log / parameters.gamma,
        eta=parameters.A * math.exp(-(1.0 + parameters.k / parameters.gamma) * ratio_log),
        alpha=0.5 * parameters.k * parameters.gamma * parameters.sigma**2,
        beta=parameters.k * parameters.mu,
    )


def inventory_grid(parameters: GLFTParameters) -> NDArray[np.int64]:
    """Return the ordered inventory states ``-Q, ..., Q``."""

    bound = int(parameters.max_inventory)
    return np.arange(-bound, bound + 1, dtype=np.int64)


def glft_matrix(parameters: GLFTParameters) -> NDArray[np.float64]:
    """Build the exact tridiagonal matrix ``M`` from the GLFT paper.

    Its diagonal is ``alpha * q**2 - beta * q`` and both adjacent diagonals
    are ``-eta``.  No regularizer or additional diagonal term is introduced.
    """

    constants = glft_constants(parameters)
    grid = inventory_grid(parameters).astype(np.float64)
    size = grid.size
    matrix = np.zeros((size, size), dtype=np.float64)
    np.fill_diagonal(matrix, constants.alpha * np.square(grid) - constants.beta * grid)
    adjacent = np.arange(size - 1)
    matrix[adjacent, adjacent + 1] = -constants.eta
    matrix[adjacent + 1, adjacent] = -constants.eta
    return matrix


def _value_from_matrix(matrix: NDArray[np.float64], time_to_horizon: float) -> NDArray[np.float64]:
    value = expm(-matrix * time_to_horizon) @ np.ones(matrix.shape[0])
    if not np.all(np.isfinite(value)) or not np.all(value > 0.0):
        raise FloatingPointError("the GLFT value vector is not positive and finite")
    return value


def _time_to_horizon(t: float, horizon: float) -> float:
    if not math.isfinite(t) or not math.isfinite(horizon):
        raise ValueError("t and horizon must be finite")
    if horizon < 0.0 or t < 0.0 or t > horizon:
        raise ValueError("expected 0 <= t <= horizon")
    return horizon - t


@lru_cache(maxsize=128)
def _relative_eigensystem(
    parameters: GLFTParameters,
) -> tuple[NDArray[np.float64], NDArray[np.float64]]:
    eigenvalues, eigenvectors = np.linalg.eigh(glft_matrix(parameters))
    eigenvalues.setflags(write=False)
    eigenvectors.setflags(write=False)
    return eigenvalues, eigenvectors


def _relative_value_from_eigensystem(
    eigenvalues: NDArray[np.float64],
    eigenvectors: NDArray[np.float64],
    time_to_horizon: float,
) -> NDArray[np.float64]:
    """Return ``v`` up to a positive scalar, without exponential overflow.

    For the smallest eigenvalue ``lambda_min``, this computes
    ``exp(lambda_min * tau) * exp(-M * tau) @ 1``.  Every exponent is therefore
    non-positive, while all adjacent value ratios used by GLFT remain exact.
    """

    size = eigenvalues.size
    if time_to_horizon == 0.0:
        return np.ones(size, dtype=np.float64)
    shifted_decay = np.exp(-(eigenvalues - eigenvalues[0]) * time_to_horizon)
    terminal_projection = eigenvectors.T @ np.ones(size, dtype=np.float64)
    value = eigenvectors @ (shifted_decay * terminal_projection)
    if not np.all(np.isfinite(value)) or not np.all(value > 0.0):
        raise FloatingPointError("the relative GLFT value vector is not positive and finite")
    return value


def _relative_value(parameters: GLFTParameters, time_to_horizon: float) -> NDArray[np.float64]:
    return _relative_value_from_eigensystem(*_relative_eigensystem(parameters), time_to_horizon)


def finite_horizon_value(
    parameters: GLFTParameters, t: float, horizon: float
) -> NDArray[np.float64]:
    """Compute ``v(t) = exp(-M * (T - t)) @ 1`` exactly."""

    return _value_from_matrix(glft_matrix(parameters), _time_to_horizon(t, horizon))


def _deltas_from_value(
    parameters: GLFTParameters,
    inventory: int,
    value: NDArray[np.float64],
) -> QuoteDeltas:
    bound = int(parameters.max_inventory)
    index = inventory + bound
    c = glft_constants(parameters).c

    bid_delta = None
    if inventory < bound:
        bid_delta = c + (math.log(value[index]) - math.log(value[index + 1])) / parameters.k

    ask_delta = None
    if inventory > -bound:
        ask_delta = c + (math.log(value[index]) - math.log(value[index - 1])) / parameters.k

    return QuoteDeltas(bid_delta=bid_delta, ask_delta=ask_delta)


def optimal_deltas(
    parameters: GLFTParameters,
    inventory: int,
    t: float,
    horizon: float,
) -> QuoteDeltas:
    """Return the exact finite-horizon bid and ask deltas at inventory ``q``.

    The bid is absent at ``q = Q`` and the ask is absent at ``q = -Q`` so the
    returned policy cannot move inventory outside the modeled state space.
    """

    if (
        isinstance(inventory, bool)
        or not isinstance(inventory, Integral)
        or abs(inventory) > parameters.max_inventory
    ):
        raise ValueError("inventory must be an integer in [-Q, Q]")
    value = _relative_value(parameters, _time_to_horizon(t, horizon))
    return _deltas_from_value(parameters, int(inventory), value)


def poisson_fill_intensity(parameters: GLFTParameters, delta: float) -> float:
    """Return the theoretical GLFT intensity ``A * exp(-k * delta)``."""

    if not math.isfinite(delta):
        raise ValueError("delta must be finite")
    return parameters.A * math.exp(-parameters.k * delta)


def _time_grid(horizon: float, dt: float) -> NDArray[np.float64]:
    ratio = horizon / dt
    nearest_integer = round(ratio)
    if math.isclose(ratio, nearest_integer, rel_tol=1e-12, abs_tol=1e-12):
        step_count = max(1, int(nearest_integer))
    else:
        step_count = math.ceil(ratio)
    time = np.minimum(np.arange(step_count + 1, dtype=np.float64) * dt, horizon)
    time[-1] = horizon
    return time


def simulate_poisson_benchmark(
    parameters: GLFTParameters,
    *,
    horizon: float,
    dt: float,
    initial_mid_price: float,
    initial_inventory: int = 0,
    initial_cash: float = 0.0,
    seed: int = 0,
) -> TheoreticalPoissonSimulation:
    """Simulate the GLFT theoretical benchmark with independent Poisson fills.

    During each interval, bid and ask fill counts are sampled independently
    from Poisson laws with the paper intensity and then capped only by the
    inventory boundary.  The mid follows the paper's arithmetic Brownian
    motion.  This function intentionally does not emulate FIFO queues,
    latency, partial order priority or adverse selection.
    """

    scalar_inputs = (horizon, dt, initial_mid_price, initial_cash)
    if not all(math.isfinite(value) for value in scalar_inputs):
        raise ValueError("simulation inputs must be finite")
    if horizon <= 0.0 or dt <= 0.0:
        raise ValueError("horizon and dt must be strictly positive")
    if (
        isinstance(initial_inventory, bool)
        or not isinstance(initial_inventory, Integral)
        or abs(initial_inventory) > parameters.max_inventory
    ):
        raise ValueError("initial_inventory must be an integer inside the bounds")

    seed = int(seed)
    rng = np.random.default_rng(seed)
    time = _time_grid(horizon, dt)
    durations = np.diff(time)
    step_count = durations.size

    mid_price = np.empty(step_count + 1, dtype=np.float64)
    inventory = np.empty(step_count + 1, dtype=np.int64)
    cash = np.empty(step_count + 1, dtype=np.float64)
    equity = np.empty(step_count + 1, dtype=np.float64)
    bid_delta = np.full(step_count, np.nan, dtype=np.float64)
    ask_delta = np.full(step_count, np.nan, dtype=np.float64)
    bid_price = np.full(step_count, np.nan, dtype=np.float64)
    ask_price = np.full(step_count, np.nan, dtype=np.float64)
    bid_fills = np.zeros(step_count, dtype=np.int64)
    ask_fills = np.zeros(step_count, dtype=np.int64)

    mid_price[0] = initial_mid_price
    inventory[0] = int(initial_inventory)
    cash[0] = initial_cash
    equity[0] = initial_cash + initial_inventory * initial_mid_price

    eigenvalues, eigenvectors = _relative_eigensystem(parameters)
    bound = int(parameters.max_inventory)

    for index, step in enumerate(durations):
        current_inventory = int(inventory[index])
        value = _relative_value_from_eigensystem(eigenvalues, eigenvectors, horizon - time[index])
        deltas = _deltas_from_value(parameters, current_inventory, value)

        if deltas.bid_delta is not None:
            bid_delta[index] = deltas.bid_delta
            bid_price[index] = mid_price[index] - deltas.bid_delta
            bid_capacity = bound - current_inventory
            bid_fills[index] = min(
                int(rng.poisson(poisson_fill_intensity(parameters, deltas.bid_delta) * step)),
                bid_capacity,
            )

        if deltas.ask_delta is not None:
            ask_delta[index] = deltas.ask_delta
            ask_price[index] = mid_price[index] + deltas.ask_delta
            ask_capacity = current_inventory + bound
            ask_fills[index] = min(
                int(rng.poisson(poisson_fill_intensity(parameters, deltas.ask_delta) * step)),
                ask_capacity,
            )

        inventory[index + 1] = current_inventory + bid_fills[index] - ask_fills[index]
        bid_notional = bid_fills[index] * bid_price[index] if deltas.bid_delta is not None else 0.0
        ask_notional = ask_fills[index] * ask_price[index] if deltas.ask_delta is not None else 0.0
        cash[index + 1] = cash[index] - bid_notional + ask_notional
        mid_price[index + 1] = (
            mid_price[index]
            + parameters.mu * step
            + parameters.sigma * math.sqrt(step) * rng.normal()
        )
        equity[index + 1] = cash[index + 1] + inventory[index + 1] * mid_price[index + 1]

    return TheoreticalPoissonSimulation(
        label=THEORETICAL_BENCHMARK_LABEL,
        seed=seed,
        time=time,
        step_duration=durations,
        mid_price=mid_price,
        inventory=inventory,
        cash=cash,
        equity=equity,
        bid_delta=bid_delta,
        ask_delta=ask_delta,
        bid_price=bid_price,
        ask_price=ask_price,
        bid_fills=bid_fills,
        ask_fills=ask_fills,
    )
