"""Causal event-driven execution replay for GLFT experiments.

The replay deliberately separates theoretical GLFT quoting from empirical execution.
It consumes top-of-book and aggressive-trade events and never reconstructs information
that was not observable at the event timestamp.  Linear accounting settles cash in the
quote asset.  Inverse accounting treats quantities as contracts with a fixed quote-asset
face value, settles fees and PnL in the base asset, and rejects quantities that do not
respect the configured contract step.  Funding, margin requirements, and forced exchange
liquidations are outside this execution replay; ``liquidate_at_end`` is only a terminal
close at the observed touch.

Queue model
-----------
Only top-of-book (for example Binance ``bookTicker``) quantities are available.  The
``queue_ahead`` field is therefore an explicitly labelled approximation, not a claim of
full L2/FIFO reconstruction:

* joining the displayed best quote starts behind its displayed quantity;
* improving the best quote starts with zero external quantity ahead;
* an order away from the displayed best has unknown queue position and cannot consume an
  exact-price trade until that price is observed at the top of book (a print strictly
  through the limit is direct evidence that the resting order was crossed);
* displayed quantity reductions never improve an existing order's queue position because
  they may be cancellations behind it; only aggressive volume depletes queue ahead;
* cancellations of our own earlier orders do reduce the queue ahead of our later orders.

Tie policy
----------
Events are replayed in timestamp order, independently of input order.  At one timestamp:

1. market events run by source ``sequence`` (book before trade only on an exact tie);
2. cancel acknowledgements already in flight run;
3. placement acknowledgements already in flight run;
4. external and closed-loop strategy requests run by ``sequence``;
5. zero-latency acknowledgements generated by those requests run cancel-first.

Consequently a trade tied with activation is too early to fill the order, while a trade
tied with cancellation can still fill it.  This conservative convention prevents
same-timestamp lookahead when the source does not provide a total exchange sequence.
Sequence values from independent feeds are not a total order and must not be compared
directly; adapters must replace them with a synthetic order preserving the merged stream.
"""

from __future__ import annotations

from bisect import bisect_left
from collections.abc import Iterable
from dataclasses import dataclass
from decimal import ROUND_CEILING, ROUND_FLOOR, Decimal
from enum import Enum
from heapq import heappop, heappush
from math import isfinite
from typing import Protocol, TypeAlias

EPSILON = 1e-12
QUEUE_MODEL_DESCRIPTION = (
    "conservative top-of-book/bookTicker queue-ahead approximation; not L2/FIFO reconstruction"
)
TIE_POLICY_DESCRIPTION = (
    "timestamp; market(sequence, book-before-trade exact tie); in-flight cancel; "
    "in-flight placement; external/closed-loop strategy request; "
    "zero-latency cancel then placement"
)


class Side(str, Enum):
    """Order or aggressor side."""

    BUY = "buy"
    SELL = "sell"

    @property
    def sign(self) -> int:
        return 1 if self is Side.BUY else -1

    @property
    def opposite(self) -> Side:
        return Side.SELL if self is Side.BUY else Side.BUY


class OrderStatus(str, Enum):
    PENDING = "pending"
    ACTIVE = "active"
    PARTIALLY_FILLED = "partially_filled"
    CANCEL_PENDING = "cancel_pending"
    FILLED = "filled"
    CANCELED = "canceled"
    REJECTED = "rejected"
    EXPIRED = "expired"


class Liquidity(str, Enum):
    MAKER = "maker"
    TAKER = "taker"


class AccountingModel(str, Enum):
    """Cash and mark-to-market convention used by the replay."""

    LINEAR = "linear"
    INVERSE = "inverse"


@dataclass(frozen=True, slots=True, kw_only=True)
class BookEvent:
    """Top-of-book snapshot known at ``timestamp``."""

    timestamp: float
    bid_price: float
    bid_quantity: float
    ask_price: float
    ask_quantity: float
    sequence: int = 0


@dataclass(frozen=True, slots=True, kw_only=True)
class TradeEvent:
    """Aggressive trade; BUY aggressors consume asks and SELL aggressors consume bids."""

    timestamp: float
    price: float
    quantity: float
    aggressor_side: Side
    sequence: int = 0


@dataclass(frozen=True, slots=True, kw_only=True)
class PlaceOrderEvent:
    """Request a post-only maker limit order."""

    timestamp: float
    order_id: str
    side: Side
    price: float
    quantity: float
    sequence: int = 0


@dataclass(frozen=True, slots=True, kw_only=True)
class CancelOrderEvent:
    """Request cancellation of one order by id."""

    timestamp: float
    order_id: str
    sequence: int = 0


@dataclass(frozen=True, slots=True, kw_only=True)
class QuoteEvent:
    """Cancel/replace the current one-sided or two-sided quote.

    A ``None`` price (with zero quantity) withdraws that side.  Repeating an identical
    rounded price and quantity keeps the existing order, queue priority, and quote age.
    Replacements become eligible only after both placement latency and the old order's
    cancellation latency have elapsed.
    """

    timestamp: float
    bid_price: float | None = None
    bid_quantity: float = 0.0
    ask_price: float | None = None
    ask_quantity: float = 0.0
    quote_id: str = "quote"
    sequence: int = 0


@dataclass(frozen=True, slots=True)
class ReplayStrategyState:
    """Causal state exposed to a closed-loop quoting policy after a book update."""

    timestamp: float
    book: BookEvent
    cash: float
    inventory: float


class BookQuotePolicy(Protocol):
    """Minimal interface for inventory-aware quote generation during replay."""

    def on_book(self, state: ReplayStrategyState) -> QuoteEvent | None:
        """Return a quote request based only on the supplied causal state."""


ReplayEvent: TypeAlias = BookEvent | TradeEvent | PlaceOrderEvent | CancelOrderEvent | QuoteEvent


@dataclass(frozen=True, slots=True)
class ReplayConfig:
    tick_size: float
    placement_latency: float = 0.0
    cancel_latency: float = 0.0
    maker_fee_rate: float = 0.0
    taker_fee_rate: float = 0.0
    initial_cash: float = 0.0
    initial_inventory: float = 0.0
    liquidate_at_end: bool = True
    markout_horizons: tuple[float, ...] = (1.0, 5.0, 30.0)
    accounting_model: AccountingModel = AccountingModel.LINEAR
    contract_multiplier: float = 1.0
    initial_entry_price: float | None = None
    quantity_step: float | None = None

    def __post_init__(self) -> None:
        _require_positive("tick_size", self.tick_size)
        _require_non_negative("placement_latency", self.placement_latency)
        _require_non_negative("cancel_latency", self.cancel_latency)
        _require_finite("maker_fee_rate", self.maker_fee_rate)
        _require_finite("taker_fee_rate", self.taker_fee_rate)
        _require_finite("initial_cash", self.initial_cash)
        _require_finite("initial_inventory", self.initial_inventory)
        try:
            model = AccountingModel(self.accounting_model)
        except ValueError as exc:
            raise ValueError("accounting_model must be 'linear' or 'inverse'") from exc
        object.__setattr__(self, "accounting_model", model)
        _require_positive("contract_multiplier", self.contract_multiplier)
        if self.initial_entry_price is not None:
            _require_positive("initial_entry_price", self.initial_entry_price)
        if self.quantity_step is not None:
            _require_positive("quantity_step", self.quantity_step)
        if self.maker_fee_rate <= -1.0 or self.taker_fee_rate <= -1.0:
            raise ValueError("fee rates must be greater than -1")
        if model is AccountingModel.INVERSE:
            if abs(self.initial_inventory) > EPSILON and self.initial_entry_price is None:
                raise ValueError("inverse initial_inventory requires initial_entry_price")
            if self.quantity_step is None:
                object.__setattr__(self, "quantity_step", 1.0)
        if self.quantity_step is not None and not _is_step_multiple(
            self.initial_inventory, self.quantity_step
        ):
            raise ValueError("initial_inventory must be a quantity_step multiple")
        for horizon in self.markout_horizons:
            _require_non_negative("markout horizon", horizon)

    @property
    def cash_unit(self) -> str:
        return "base_asset" if self.accounting_model is AccountingModel.INVERSE else "quote_asset"


@dataclass(slots=True)
class Order:
    order_id: str
    side: Side
    requested_price: float
    price: float
    quantity: float
    requested_at: float
    activation_at: float
    sequence: int
    quote_id: str | None = None
    status: OrderStatus = OrderStatus.PENDING
    active_at: float | None = None
    cancel_requested_at: float | None = None
    cancel_effective_at: float | None = None
    canceled_at: float | None = None
    filled_quantity: float = 0.0
    queue_ahead: float | None = None
    initial_queue_ahead: float | None = None
    rejection_reason: str | None = None

    @property
    def remaining_quantity(self) -> float:
        return max(0.0, self.quantity - self.filled_quantity)

    @property
    def is_terminal(self) -> bool:
        return self.status in {
            OrderStatus.FILLED,
            OrderStatus.CANCELED,
            OrderStatus.REJECTED,
            OrderStatus.EXPIRED,
        }

    @property
    def is_live(self) -> bool:
        """Whether the order is active at the simulated exchange."""

        return self.active_at is not None and not self.is_terminal

    def age_at(self, timestamp: float) -> float:
        """Active quote age, excluding placement latency."""

        if self.active_at is None:
            return 0.0
        return max(0.0, timestamp - self.active_at)


@dataclass(frozen=True, slots=True)
class FillRecord:
    timestamp: float
    order_id: str
    side: Side
    price: float
    quantity: float
    notional: float
    fee: float
    liquidity: Liquidity
    cash_after: float
    inventory_after: float
    quote_age: float
    is_liquidation: bool = False
    settlement_notional: float = 0.0
    realized_pnl: float = 0.0
    average_entry_price_after: float | None = None


@dataclass(frozen=True, slots=True)
class EquityPoint:
    timestamp: float
    cash: float
    inventory: float
    mid_price: float
    equity: float
    reason: str
    position_value: float = 0.0
    average_entry_price: float | None = None


@dataclass(frozen=True, slots=True)
class MarkoutRecord:
    fill_order_id: str
    fill_timestamp: float
    horizon: float
    observed_at: float | None
    reference_mid: float | None
    signed_pnl_per_unit: float | None
    signed_bps: float | None


@dataclass(frozen=True, slots=True)
class ProcessedEvent:
    ordinal: int
    timestamp: float
    event_type: str
    sequence: int
    order_id: str | None = None


@dataclass(frozen=True, slots=True)
class ReplayResult:
    orders: dict[str, Order]
    fills: tuple[FillRecord, ...]
    markouts: tuple[MarkoutRecord, ...]
    equity_curve: tuple[EquityPoint, ...]
    processed_events: tuple[ProcessedEvent, ...]
    final_cash: float
    final_inventory: float
    final_equity: float
    final_mid_price: float | None
    queue_model: str = QUEUE_MODEL_DESCRIPTION
    tie_policy: str = TIE_POLICY_DESCRIPTION
    accounting_model: AccountingModel = AccountingModel.LINEAR
    contract_multiplier: float = 1.0
    quantity_step: float | None = None
    cash_unit: str = "quote_asset"
    final_average_entry_price: float | None = None

    def order(self, order_id: str) -> Order:
        return self.orders[order_id]


@dataclass(frozen=True, slots=True)
class _Activation:
    timestamp: float
    order_id: str
    sequence: int


@dataclass(frozen=True, slots=True)
class _Cancellation:
    timestamp: float
    order_id: str
    sequence: int


class EventDrivenReplay:
    """Replay post-only maker execution against causal BBO and trade events."""

    def __init__(self, config: ReplayConfig):
        self.config = config
        self._reset()

    def run(
        self,
        events: Iterable[ReplayEvent],
        *,
        quote_policy: BookQuotePolicy | None = None,
        events_are_sorted: bool = False,
    ) -> ReplayResult:
        """Replay events in canonical order and return immutable records.

        Input order is intentionally irrelevant.  ``sequence`` must be populated from the
        source whenever multiple messages from one exchange feed share one timestamp.
        Independent feeds require synthetic comparable sequences preserving their merged
        order.  A ``quote_policy`` is called only after all market messages and in-flight
        acknowledgements at that timestamp have been processed.  Set
        ``events_are_sorted=True`` only for a canonically ordered list; this avoids an
        extra list copy and sort for bounded-window adapters.
        """

        self._reset()
        external = events if events_are_sorted and isinstance(events, list) else list(events)
        for event in external:
            _validate_event(event)
            self._validate_contract_units(event)
        if events_are_sorted:
            keys = (_external_sort_key(event) for event in external)
            try:
                previous_key = next(keys)
            except StopIteration:
                previous_key = None
            for key in keys:
                if previous_key is not None and key < previous_key:
                    raise ValueError("events_are_sorted=True but events are not canonical")
                previous_key = key
        else:
            external.sort(key=_external_sort_key)

        if not external:
            return self._finish(0.0)

        end_time = max(event.timestamp for event in external)
        by_time: dict[float, list[ReplayEvent]] = {}
        timeline: list[float] = []
        queued_times: set[float] = set()
        for event in external:
            by_time.setdefault(event.timestamp, []).append(event)
            if event.timestamp not in queued_times:
                heappush(timeline, event.timestamp)
                queued_times.add(event.timestamp)

        while timeline:
            timestamp = heappop(timeline)
            queued_times.discard(timestamp)
            if timestamp > end_time + EPSILON:
                break

            same_time = sorted(by_time.pop(timestamp, ()), key=_external_sort_key)
            market = [event for event in same_time if isinstance(event, (BookEvent, TradeEvent))]
            commands = [
                event for event in same_time if not isinstance(event, (BookEvent, TradeEvent))
            ]

            for event in market:
                self._process_market_event(event)

            self._process_scheduled(timestamp, cancel_first=True)

            if quote_policy is not None and any(isinstance(event, BookEvent) for event in market):
                if self._book is None:  # pragma: no cover - guarded by the condition
                    raise AssertionError("book callback requested without a book")
                quote = quote_policy.on_book(
                    ReplayStrategyState(
                        timestamp=timestamp,
                        book=self._book,
                        cash=self._cash,
                        inventory=self._inventory,
                    )
                )
                if quote is not None:
                    if not isinstance(quote, QuoteEvent):
                        raise TypeError("quote_policy.on_book must return QuoteEvent or None")
                    _validate_event(quote)
                    self._validate_contract_units(quote)
                    if abs(quote.timestamp - timestamp) > EPSILON:
                        raise ValueError(
                            "closed-loop QuoteEvent timestamp must equal the book timestamp"
                        )
                    commands.append(quote)

            commands.sort(key=_external_sort_key)

            for event in commands:
                self._process_command(event, timeline, queued_times, end_time)

            # Zero-latency acknowledgements generated by commands at this timestamp.
            self._process_scheduled(timestamp, cancel_first=True)

        return self._finish(end_time)

    def _reset(self) -> None:
        self._orders: dict[str, Order] = {}
        self._fills: list[FillRecord] = []
        self._equity: list[EquityPoint] = []
        self._processed: list[ProcessedEvent] = []
        self._book: BookEvent | None = None
        self._book_history: list[tuple[float, int, float]] = []
        self._cash = self.config.initial_cash
        self._inventory = self.config.initial_inventory
        self._average_entry_price = (
            self.config.initial_entry_price
            if self.config.accounting_model is AccountingModel.INVERSE
            and abs(self._inventory) > EPSILON
            else None
        )
        self._activations: dict[float, list[_Activation]] = {}
        self._cancellations: dict[float, list[_Cancellation]] = {}
        self._quote_order_by_side: dict[Side, str] = {}
        self._quote_counter = 0

    def _process_market_event(self, event: BookEvent | TradeEvent) -> None:
        if isinstance(event, BookEvent):
            self._book = event
            mid = (event.bid_price + event.ask_price) / 2.0
            self._book_history.append((event.timestamp, event.sequence, mid))
            self._initialize_newly_visible_queues(event)
            self._log(event.timestamp, "book", event.sequence)
            self._record_equity(event.timestamp, "book")
            return

        self._log(event.timestamp, "trade", event.sequence)
        self._process_trade(event)

    def _validate_contract_units(self, event: ReplayEvent) -> None:
        if self.config.accounting_model is not AccountingModel.INVERSE:
            return
        step = self.config.quantity_step
        if step is None:  # pragma: no cover - set by ReplayConfig
            raise AssertionError("inverse accounting has no quantity_step")

        quantities: tuple[tuple[str, float], ...]
        if isinstance(event, BookEvent):
            quantities = (
                ("book bid quantity", event.bid_quantity),
                ("book ask quantity", event.ask_quantity),
            )
        elif isinstance(event, TradeEvent):
            quantities = (("trade quantity", event.quantity),)
        elif isinstance(event, PlaceOrderEvent):
            quantities = (("order quantity", event.quantity),)
        elif isinstance(event, QuoteEvent):
            quantities = (
                ("bid order quantity", event.bid_quantity),
                ("ask order quantity", event.ask_quantity),
            )
        else:
            return

        for label, quantity in quantities:
            if not _is_step_multiple(quantity, step):
                raise ValueError(
                    f"inverse {label} must be a quantity_step multiple; "
                    "fractional contract units indicate a mismatched or normalized source"
                )

    def _process_command(
        self,
        event: PlaceOrderEvent | CancelOrderEvent | QuoteEvent,
        timeline: list[float],
        queued_times: set[float],
        end_time: float,
    ) -> None:
        if isinstance(event, PlaceOrderEvent):
            self._log(event.timestamp, "place_request", event.sequence, event.order_id)
            self._create_order(
                order_id=event.order_id,
                side=event.side,
                requested_price=event.price,
                quantity=event.quantity,
                timestamp=event.timestamp,
                sequence=event.sequence,
                quote_id=None,
                not_before=event.timestamp,
                timeline=timeline,
                queued_times=queued_times,
                end_time=end_time,
            )
            return

        if isinstance(event, CancelOrderEvent):
            self._log(event.timestamp, "cancel_request", event.sequence, event.order_id)
            self._request_cancel(
                event.order_id,
                event.timestamp,
                event.sequence,
                timeline,
                queued_times,
                end_time,
            )
            return

        self._log(event.timestamp, "quote_request", event.sequence, event.quote_id)
        self._process_quote(event, timeline, queued_times, end_time)

    def _process_quote(
        self,
        event: QuoteEvent,
        timeline: list[float],
        queued_times: set[float],
        end_time: float,
    ) -> None:
        for side, requested_price, quantity in (
            (Side.BUY, event.bid_price, event.bid_quantity),
            (Side.SELL, event.ask_price, event.ask_quantity),
        ):
            current_id = self._quote_order_by_side.get(side)
            current = self._orders.get(current_id) if current_id is not None else None

            if requested_price is None:
                if current is not None and not current.is_terminal:
                    self._request_cancel(
                        current.order_id,
                        event.timestamp,
                        event.sequence,
                        timeline,
                        queued_times,
                        end_time,
                    )
                self._quote_order_by_side.pop(side, None)
                continue

            rounded = round_to_tick(requested_price, side, self.config.tick_size)
            if (
                current is not None
                and current.status is not OrderStatus.CANCEL_PENDING
                and not current.is_terminal
                and _same_price(current.price, rounded, self.config.tick_size)
                and abs(current.quantity - quantity) <= EPSILON
            ):
                continue

            not_before = event.timestamp
            if current is not None and not current.is_terminal:
                cancellation_at = self._request_cancel(
                    current.order_id,
                    event.timestamp,
                    event.sequence,
                    timeline,
                    queued_times,
                    end_time,
                )
                if cancellation_at is not None:
                    not_before = max(not_before, cancellation_at)

            self._quote_counter += 1
            order_id = f"{event.quote_id}:{side.value}:{self._quote_counter}"
            self._quote_order_by_side[side] = order_id
            self._create_order(
                order_id=order_id,
                side=side,
                requested_price=requested_price,
                quantity=quantity,
                timestamp=event.timestamp,
                sequence=event.sequence,
                quote_id=event.quote_id,
                not_before=not_before,
                timeline=timeline,
                queued_times=queued_times,
                end_time=end_time,
            )

    def _create_order(
        self,
        *,
        order_id: str,
        side: Side,
        requested_price: float,
        quantity: float,
        timestamp: float,
        sequence: int,
        quote_id: str | None,
        not_before: float,
        timeline: list[float],
        queued_times: set[float],
        end_time: float,
    ) -> None:
        if order_id in self._orders:
            raise ValueError(f"duplicate order_id: {order_id}")
        if self.config.quantity_step is not None and not _is_step_multiple(
            quantity, self.config.quantity_step
        ):
            raise ValueError("order quantity must be a quantity_step multiple")
        price = round_to_tick(requested_price, side, self.config.tick_size)
        activation_at = max(timestamp + self.config.placement_latency, not_before)
        order = Order(
            order_id=order_id,
            side=side,
            requested_price=requested_price,
            price=price,
            quantity=quantity,
            requested_at=timestamp,
            activation_at=activation_at,
            sequence=sequence,
            quote_id=quote_id,
        )
        self._orders[order_id] = order
        self._activations.setdefault(activation_at, []).append(
            _Activation(activation_at, order_id, sequence)
        )
        self._queue_time(activation_at, timeline, queued_times, end_time)

    def _request_cancel(
        self,
        order_id: str,
        timestamp: float,
        sequence: int,
        timeline: list[float],
        queued_times: set[float],
        end_time: float,
    ) -> float | None:
        order = self._orders.get(order_id)
        if order is None or order.is_terminal:
            return None
        if order.status is OrderStatus.CANCEL_PENDING:
            return order.cancel_effective_at

        cancellation_at = timestamp + self.config.cancel_latency
        order.cancel_requested_at = timestamp
        order.cancel_effective_at = cancellation_at
        order.status = OrderStatus.CANCEL_PENDING
        self._cancellations.setdefault(cancellation_at, []).append(
            _Cancellation(cancellation_at, order_id, sequence)
        )
        self._queue_time(cancellation_at, timeline, queued_times, end_time)
        return cancellation_at

    @staticmethod
    def _queue_time(
        timestamp: float,
        timeline: list[float],
        queued_times: set[float],
        end_time: float,
    ) -> None:
        if timestamp <= end_time + EPSILON and timestamp not in queued_times:
            heappush(timeline, timestamp)
            queued_times.add(timestamp)

    def _process_scheduled(self, timestamp: float, *, cancel_first: bool) -> None:
        cancellations = sorted(
            self._cancellations.pop(timestamp, ()), key=lambda item: (item.sequence, item.order_id)
        )
        activations = sorted(
            self._activations.pop(timestamp, ()), key=lambda item: (item.sequence, item.order_id)
        )
        groups = (cancellations, activations) if cancel_first else (activations, cancellations)
        for group in groups:
            for item in group:
                if isinstance(item, _Cancellation):
                    self._cancel(item)
                else:
                    self._activate(item)

    def _activate(self, activation: _Activation) -> None:
        order = self._orders[activation.order_id]
        if order.is_terminal or order.active_at is not None:
            return

        if self._book is None:
            order.status = OrderStatus.REJECTED
            order.rejection_reason = "post-only activation requires a previously observed book"
            self._log(
                activation.timestamp, "placement_rejected", activation.sequence, order.order_id
            )
            return

        crosses = (order.side is Side.BUY and order.price >= self._book.ask_price - EPSILON) or (
            order.side is Side.SELL and order.price <= self._book.bid_price + EPSILON
        )
        if crosses:
            order.status = OrderStatus.REJECTED
            order.rejection_reason = "post-only order would cross the observed book"
            self._log(
                activation.timestamp, "placement_rejected", activation.sequence, order.order_id
            )
            return

        cancel_in_flight = order.status is OrderStatus.CANCEL_PENDING
        order.active_at = activation.timestamp
        order.queue_ahead = self._initial_queue_ahead(order)
        order.initial_queue_ahead = order.queue_ahead
        order.status = OrderStatus.CANCEL_PENDING if cancel_in_flight else OrderStatus.ACTIVE
        self._log(activation.timestamp, "placement_ack", activation.sequence, order.order_id)

    def _cancel(self, cancellation: _Cancellation) -> None:
        order = self._orders[cancellation.order_id]
        if order.is_terminal:
            return

        if order.is_live:
            self._remove_known_own_queue(order)
        order.status = OrderStatus.CANCELED
        order.canceled_at = cancellation.timestamp
        self._log(cancellation.timestamp, "cancel_ack", cancellation.sequence, order.order_id)

    def _remove_known_own_queue(self, canceled: Order) -> None:
        canceled_priority = _order_priority(canceled)
        for order in self._orders.values():
            if (
                order.is_live
                and order.side is canceled.side
                and _same_price(order.price, canceled.price, self.config.tick_size)
                and _order_priority(order) > canceled_priority
                and order.queue_ahead is not None
            ):
                order.queue_ahead = max(0.0, order.queue_ahead - canceled.remaining_quantity)

    def _initial_queue_ahead(self, order: Order) -> float | None:
        assert self._book is not None
        if order.side is Side.BUY:
            if _same_price(order.price, self._book.bid_price, self.config.tick_size):
                external = self._book.bid_quantity
            elif self._book.bid_price < order.price < self._book.ask_price:
                external = 0.0
            else:
                return None
        else:
            if _same_price(order.price, self._book.ask_price, self.config.tick_size):
                external = self._book.ask_quantity
            elif self._book.bid_price < order.price < self._book.ask_price:
                external = 0.0
            else:
                return None

        own_ahead = sum(
            candidate.remaining_quantity
            for candidate in self._orders.values()
            if candidate.order_id != order.order_id
            and candidate.is_live
            and candidate.side is order.side
            and _same_price(candidate.price, order.price, self.config.tick_size)
            and _order_priority(candidate) < _order_priority(order)
        )
        return external + own_ahead

    def _initialize_newly_visible_queues(self, book: BookEvent) -> None:
        for order in self._orders.values():
            if not order.is_live or order.queue_ahead is not None:
                continue
            visible = (
                order.side is Side.BUY
                and _same_price(order.price, book.bid_price, self.config.tick_size)
            ) or (
                order.side is Side.SELL
                and _same_price(order.price, book.ask_price, self.config.tick_size)
            )
            if visible:
                order.queue_ahead = self._initial_queue_ahead(order)
                if order.initial_queue_ahead is None:
                    order.initial_queue_ahead = order.queue_ahead

    def _process_trade(self, trade: TradeEvent) -> None:
        maker_side = trade.aggressor_side.opposite
        live = [
            order
            for order in self._orders.values()
            if order.is_live and order.side is maker_side and order.remaining_quantity > EPSILON
        ]
        live.sort(key=_order_priority)

        exact: list[Order] = []
        for order in live:
            if _traded_through(order, trade.price, self.config.tick_size):
                self._fill_order(order, order.remaining_quantity, order.price, trade.timestamp)
            elif _same_price(order.price, trade.price, self.config.tick_size):
                exact.append(order)

        # Every order's queue_ahead is an absolute amount in front of that order at this
        # price, so the same aggressive quantity is applied to each threshold.  This
        # preserves FIFO across multiple simulated orders at one level.
        for order in exact:
            if not order.is_live or order.queue_ahead is None:
                continue
            ahead_before = order.queue_ahead
            order.queue_ahead = max(0.0, ahead_before - trade.quantity)
            executable = max(0.0, trade.quantity - ahead_before)
            fill_quantity = min(order.remaining_quantity, executable)
            if fill_quantity > EPSILON:
                self._fill_order(order, fill_quantity, order.price, trade.timestamp)

    def _fill_order(self, order: Order, quantity: float, price: float, timestamp: float) -> None:
        quantity = min(quantity, order.remaining_quantity)
        if quantity <= EPSILON:
            return
        notional, settlement_notional, fee, realized_pnl = self._apply_fill_financials(
            order.side,
            quantity,
            price,
            self.config.maker_fee_rate,
        )
        order.filled_quantity += quantity
        if order.remaining_quantity <= EPSILON:
            order.filled_quantity = order.quantity
            order.status = OrderStatus.FILLED
        elif order.cancel_requested_at is not None:
            order.status = OrderStatus.CANCEL_PENDING
        else:
            order.status = OrderStatus.PARTIALLY_FILLED

        self._fills.append(
            FillRecord(
                timestamp=timestamp,
                order_id=order.order_id,
                side=order.side,
                price=price,
                quantity=quantity,
                notional=notional,
                fee=fee,
                liquidity=Liquidity.MAKER,
                cash_after=self._cash,
                inventory_after=self._inventory,
                quote_age=order.age_at(timestamp),
                settlement_notional=settlement_notional,
                realized_pnl=realized_pnl,
                average_entry_price_after=self._average_entry_price,
            )
        )
        self._record_equity(timestamp, "maker_fill")

    def _apply_fill_financials(
        self,
        side: Side,
        quantity: float,
        price: float,
        fee_rate: float,
    ) -> tuple[float, float, float, float]:
        if self.config.accounting_model is AccountingModel.LINEAR:
            notional = price * quantity
            settlement_notional = notional
            fee = settlement_notional * fee_rate
            self._cash -= side.sign * notional + fee
            self._inventory += side.sign * quantity
            if abs(self._inventory) <= EPSILON:
                self._inventory = 0.0
            return notional, settlement_notional, fee, 0.0

        notional = self.config.contract_multiplier * quantity
        settlement_notional = notional / price
        fee = settlement_notional * fee_rate
        realized_pnl = self._apply_inverse_position(side, quantity, price)
        self._cash += realized_pnl - fee
        return notional, settlement_notional, fee, realized_pnl

    def _apply_inverse_position(
        self,
        side: Side,
        quantity: float,
        price: float,
    ) -> float:
        old_inventory = self._inventory
        old_average = self._average_entry_price
        delta = side.sign * quantity
        realized_pnl = 0.0

        if old_inventory * delta < 0.0:
            if old_average is None:
                raise AssertionError("inverse position has no entry price")
            closing_quantity = min(abs(old_inventory), quantity)
            realized_pnl = (
                self.config.contract_multiplier
                * closing_quantity
                * (1 if old_inventory > 0.0 else -1)
                * (1.0 / old_average - 1.0 / price)
            )

        new_inventory = old_inventory + delta
        if abs(new_inventory) <= EPSILON:
            new_inventory = 0.0
            new_average = None
        elif (
            abs(old_inventory) <= EPSILON
            or old_inventory * delta < 0.0
            and (quantity > abs(old_inventory) + EPSILON)
        ):
            new_average = price
        elif old_inventory * delta > 0.0:
            if old_average is None:
                raise AssertionError("inverse position has no entry price")
            total_quantity = abs(old_inventory) + quantity
            reciprocal_average = (
                abs(old_inventory) / old_average + quantity / price
            ) / total_quantity
            new_average = 1.0 / reciprocal_average
        else:
            new_average = old_average

        self._inventory = new_inventory
        self._average_entry_price = new_average
        return realized_pnl

    def _position_value(self, mark_price: float) -> float:
        if self.config.accounting_model is AccountingModel.LINEAR:
            return self._inventory * mark_price
        if abs(self._inventory) <= EPSILON:
            return 0.0
        if self._average_entry_price is None:
            raise AssertionError("inverse position has no entry price")
        return (
            self.config.contract_multiplier
            * self._inventory
            * (1.0 / self._average_entry_price - 1.0 / mark_price)
        )

    def _record_equity(self, timestamp: float, reason: str) -> None:
        if self._book is None:
            return
        mid = (self._book.bid_price + self._book.ask_price) / 2.0
        position_value = self._position_value(mid)
        self._equity.append(
            EquityPoint(
                timestamp=timestamp,
                cash=self._cash,
                inventory=self._inventory,
                mid_price=mid,
                equity=self._cash + position_value,
                reason=reason,
                position_value=position_value,
                average_entry_price=self._average_entry_price,
            )
        )

    def _finish(self, end_time: float) -> ReplayResult:
        for order in self._orders.values():
            if not order.is_terminal:
                order.status = OrderStatus.EXPIRED
                order.canceled_at = end_time

        if self.config.liquidate_at_end and abs(self._inventory) > EPSILON:
            self._liquidate(end_time)

        final_mid = None
        if self._book is not None:
            final_mid = (self._book.bid_price + self._book.ask_price) / 2.0
            final_equity = self._cash + self._position_value(final_mid)
        elif abs(self._inventory) > EPSILON:
            raise ValueError("cannot mark or liquidate non-zero inventory without a book")
        else:
            final_equity = self._cash

        return ReplayResult(
            orders=dict(self._orders),
            fills=tuple(self._fills),
            markouts=tuple(self._build_markouts()),
            equity_curve=tuple(self._equity),
            processed_events=tuple(self._processed),
            final_cash=self._cash,
            final_inventory=self._inventory,
            final_equity=final_equity,
            final_mid_price=final_mid,
            accounting_model=self.config.accounting_model,
            contract_multiplier=self.config.contract_multiplier,
            quantity_step=self.config.quantity_step,
            cash_unit=self.config.cash_unit,
            final_average_entry_price=self._average_entry_price,
        )

    def _liquidate(self, timestamp: float) -> None:
        if self._book is None:
            raise ValueError("cannot liquidate inventory without a book")
        side = Side.SELL if self._inventory > 0.0 else Side.BUY
        quantity = abs(self._inventory)
        price = self._book.bid_price if side is Side.SELL else self._book.ask_price
        notional, settlement_notional, fee, realized_pnl = self._apply_fill_financials(
            side,
            quantity,
            price,
            self.config.taker_fee_rate,
        )
        self._fills.append(
            FillRecord(
                timestamp=timestamp,
                order_id="__final_liquidation__",
                side=side,
                price=price,
                quantity=quantity,
                notional=notional,
                fee=fee,
                liquidity=Liquidity.TAKER,
                cash_after=self._cash,
                inventory_after=self._inventory,
                quote_age=0.0,
                is_liquidation=True,
                settlement_notional=settlement_notional,
                realized_pnl=realized_pnl,
                average_entry_price_after=self._average_entry_price,
            )
        )
        self._log(timestamp, "final_liquidation", 0, "__final_liquidation__")
        self._record_equity(timestamp, "final_liquidation")

    def _build_markouts(self) -> list[MarkoutRecord]:
        history = sorted(self._book_history, key=lambda item: (item[0], item[1]))
        timestamps = [item[0] for item in history]
        records: list[MarkoutRecord] = []
        for fill in self._fills:
            if fill.is_liquidation:
                continue
            for horizon in self.config.markout_horizons:
                index = bisect_left(timestamps, fill.timestamp + horizon)
                if index == len(history):
                    records.append(
                        MarkoutRecord(
                            fill_order_id=fill.order_id,
                            fill_timestamp=fill.timestamp,
                            horizon=horizon,
                            observed_at=None,
                            reference_mid=None,
                            signed_pnl_per_unit=None,
                            signed_bps=None,
                        )
                    )
                    continue
                observed_at, _, mid = history[index]
                if self.config.accounting_model is AccountingModel.INVERSE:
                    pnl = (
                        self.config.contract_multiplier
                        * fill.side.sign
                        * (1.0 / fill.price - 1.0 / mid)
                    )
                    entry_base_notional = self.config.contract_multiplier / fill.price
                    signed_bps = 10_000.0 * pnl / entry_base_notional
                else:
                    pnl = fill.side.sign * (mid - fill.price)
                    signed_bps = 10_000.0 * pnl / fill.price
                records.append(
                    MarkoutRecord(
                        fill_order_id=fill.order_id,
                        fill_timestamp=fill.timestamp,
                        horizon=horizon,
                        observed_at=observed_at,
                        reference_mid=mid,
                        signed_pnl_per_unit=pnl,
                        signed_bps=signed_bps,
                    )
                )
        return records

    def _log(
        self, timestamp: float, event_type: str, sequence: int, order_id: str | None = None
    ) -> None:
        self._processed.append(
            ProcessedEvent(
                ordinal=len(self._processed),
                timestamp=timestamp,
                event_type=event_type,
                sequence=sequence,
                order_id=order_id,
            )
        )


def round_to_tick(price: float, side: Side, tick_size: float) -> float:
    """Round conservatively: bids down and asks up to the exchange tick."""

    _require_positive("price", price)
    _require_positive("tick_size", tick_size)
    value = Decimal(str(price)) / Decimal(str(tick_size))
    rounding = ROUND_FLOOR if side is Side.BUY else ROUND_CEILING
    ticks = value.to_integral_value(rounding=rounding)
    rounded = float(ticks * Decimal(str(tick_size)))
    if rounded <= 0.0:
        raise ValueError("rounded price must be positive")
    return rounded


def _validate_event(event: ReplayEvent) -> None:
    if not isinstance(
        event, (BookEvent, TradeEvent, PlaceOrderEvent, CancelOrderEvent, QuoteEvent)
    ):
        raise TypeError(f"unsupported replay event: {type(event).__name__}")
    _require_finite("timestamp", event.timestamp)
    if not isinstance(event.sequence, int):
        raise TypeError("event sequence must be an int")

    if isinstance(event, BookEvent):
        _require_positive("bid_price", event.bid_price)
        _require_positive("ask_price", event.ask_price)
        _require_non_negative("bid_quantity", event.bid_quantity)
        _require_non_negative("ask_quantity", event.ask_quantity)
        if event.bid_price >= event.ask_price:
            raise ValueError("book must satisfy bid_price < ask_price")
    elif isinstance(event, TradeEvent):
        _require_positive("trade price", event.price)
        _require_positive("trade quantity", event.quantity)
        if not isinstance(event.aggressor_side, Side):
            raise TypeError("aggressor_side must be Side")
    elif isinstance(event, PlaceOrderEvent):
        if not event.order_id:
            raise ValueError("order_id must not be empty")
        if not isinstance(event.side, Side):
            raise TypeError("order side must be Side")
        _require_positive("order price", event.price)
        _require_positive("order quantity", event.quantity)
    elif isinstance(event, QuoteEvent):
        if not event.quote_id:
            raise ValueError("quote_id must not be empty")
        _validate_quote_side("bid", event.bid_price, event.bid_quantity)
        _validate_quote_side("ask", event.ask_price, event.ask_quantity)
    elif not event.order_id:
        raise ValueError("order_id must not be empty")


def _validate_quote_side(label: str, price: float | None, quantity: float) -> None:
    if price is None:
        if abs(quantity) > EPSILON:
            raise ValueError(f"{label}_quantity must be zero when {label}_price is None")
        return
    _require_positive(f"{label}_price", price)
    _require_positive(f"{label}_quantity", quantity)


def _external_sort_key(event: ReplayEvent) -> tuple[float, int, int, int, tuple[object, ...]]:
    market_phase = 0 if isinstance(event, (BookEvent, TradeEvent)) else 1
    kind_rank = {
        BookEvent: 0,
        TradeEvent: 1,
        CancelOrderEvent: 0,
        QuoteEvent: 1,
        PlaceOrderEvent: 2,
    }[type(event)]
    return event.timestamp, market_phase, event.sequence, kind_rank, _payload_key(event)


def _payload_key(event: ReplayEvent) -> tuple[object, ...]:
    if isinstance(event, BookEvent):
        return event.bid_price, event.ask_price, event.bid_quantity, event.ask_quantity
    if isinstance(event, TradeEvent):
        return event.price, event.quantity, event.aggressor_side.value
    if isinstance(event, PlaceOrderEvent):
        return event.order_id, event.side.value, event.price, event.quantity
    if isinstance(event, CancelOrderEvent):
        return (event.order_id,)
    return (
        event.quote_id,
        event.bid_price if event.bid_price is not None else -1.0,
        event.bid_quantity,
        event.ask_price if event.ask_price is not None else -1.0,
        event.ask_quantity,
    )


def _order_priority(order: Order) -> tuple[float, float, int, str]:
    # Better price first, then exchange activation time and deterministic request identity.
    price_priority = -order.price if order.side is Side.BUY else order.price
    active_at = order.active_at if order.active_at is not None else order.activation_at
    return price_priority, active_at, order.sequence, order.order_id


def _same_price(left: float, right: float, tick_size: float) -> bool:
    return abs(left - right) <= max(EPSILON, tick_size * 1e-9)


def _traded_through(order: Order, trade_price: float, tick_size: float) -> bool:
    tolerance = max(EPSILON, tick_size * 1e-9)
    if order.side is Side.BUY:
        return trade_price < order.price - tolerance
    return trade_price > order.price + tolerance


def _require_finite(name: str, value: float) -> None:
    if not isfinite(value):
        raise ValueError(f"{name} must be finite")


def _require_positive(name: str, value: float) -> None:
    _require_finite(name, value)
    if value <= 0.0:
        raise ValueError(f"{name} must be positive")


def _require_non_negative(name: str, value: float) -> None:
    _require_finite(name, value)
    if value < 0.0:
        raise ValueError(f"{name} must be non-negative")


def _is_step_multiple(value: float, step: float) -> bool:
    ratio = value / step
    return abs(ratio - round(ratio)) <= 1e-9


# Concise aliases for users who prefer domain nouns over event-suffixed names.
BookUpdate = BookEvent
Trade = TradeEvent
QuoteRequest = QuoteEvent
OrderRequest = PlaceOrderEvent
CancelRequest = CancelOrderEvent
ReplayEngine = EventDrivenReplay


__all__ = [
    "AccountingModel",
    "BookEvent",
    "BookQuotePolicy",
    "BookUpdate",
    "CancelOrderEvent",
    "CancelRequest",
    "EquityPoint",
    "EventDrivenReplay",
    "FillRecord",
    "Liquidity",
    "MarkoutRecord",
    "Order",
    "OrderRequest",
    "OrderStatus",
    "PlaceOrderEvent",
    "ProcessedEvent",
    "QUEUE_MODEL_DESCRIPTION",
    "QuoteEvent",
    "QuoteRequest",
    "ReplayConfig",
    "ReplayEngine",
    "ReplayResult",
    "ReplayStrategyState",
    "Side",
    "TIE_POLICY_DESCRIPTION",
    "Trade",
    "TradeEvent",
    "round_to_tick",
]
